### ISSUE TITLE
API returns irrelevent result for concept search - London

### ISSUE THREAD

**Issue by prasdeva** [bbcarchdev/spindle#112]
May belong to some other module

API search with param uri=acropolis.org.uk/?uri=http://dbpedia.org/resource/London lists results that are not related to search topic - London. In this instance results listed include

- [Des Lynam in 1994](http://acropolis.org.uk/a48a639ee49e4bd8a6530007184de651#id)

- [Single leaf on a Autumn day](http://acropolis.org.uk/9973edfc4bf24d318717370bafccdb34#id)

and many more

**Comment by nevali** [comment]
This isn't a search, it's a lookup: the *result* is the single resource, <http://acropolis.org.uk/f164436cfe8c41cc9b783dd62939f34f#id>, but the response includes data about related resources which are somehow connected.

[Des Lynam in 1994](http://acropolis.org.uk/a48a639ee49e4bd8a6530007184de651#id) has a `lio:location` relationship with [London](http://sws.geonames.org/2643743/), so in fact the API is doing precisely what it's supposed to.
