### ISSUE TITLE
Add rulebase.ttl mappings to support Cervantes Digital Library ingest

### ISSUE THREAD

**Issue by townxelliot** [bbcarchdev/spindle#129]
To ensure that Cervantes Digital Library resources go to the correct place in the RES index:

* Treat RDA Work as frbr:Work.
* Treat schema:Person as foaf:Person.

**Comment by nevali** [comment]
Hi @townxelliot  - feel free to merge this

Generally a two-line change with minimal impact shouldn't really necessitate creating a feature branch!
