### ISSUE TITLE
wrong number of results returned

### ISSUE THREAD

**Issue by simeonvandersteen** [bbcarchdev/spindle#31]
This query:

http://preview.acropolis.org.uk/?q=breakfast&media=video&limit=5

returns 4 results, while more results are available (http://preview.acropolis.org.uk/?q=breakfast&media=video&limit=5&offset=5 has results).

**Comment by nevali** [comment]
Confirmed, there's a deduping issue in the SQL query (which isn't actually resulting in duplicate results, because they get swallowed when the RDF graph is generated), but is affecting counts and offsets.
