### ISSUE TITLE
URI Template remove colon in rdfs:Class -> rdfsClass

### ISSUE THREAD

**Issue by ajtucker** [bbcarchdev/spindle#36]
Using the value of the osd:template in a URI Template (RFC6570) parser lib shows a syntax issue.  The colon (:) is reserved for declaring the maximum length of a template substitute value, see https://tools.ietf.org/html/rfc6570#section-2.4.1

**Comment by nevali** [comment]
I don't believe OpenSearch templates are intended to conform to RFC6570.

Colon-delimited form is explicitly defined in the OSD spec as an namespacing/extension mechanism:

http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_URL_template_syntax

**Comment by ajtucker** [comment]
I guess OS pre-dates URI templates. Shame. Another parser to write.
