### ISSUE TITLE
Add po:synopsis and subproperties to the rulebase

### ISSUE THREAD

**Issue by nevali** [bbcarchdev/spindle#42]

**Comment by nevali** [comment]
http://www.bbc.co.uk/ontologies/po#terms_synopsis

**Comment by bennpearson** [comment]
Should this be: 
http://www.bbc.co.uk/ontologies/po#terms_synopsis
or
http://purl.org/ontology/po/synopsis

**Comment by nevali** [comment]
@bennpearson: http://www.bbc.co.uk/ontologies/po#terms_synopsis is the link to the documentation of the property and its subproperties, not the property's URI.
