### ISSUE TITLE
Support queries for multiple audiences

### ISSUE THREAD

**Issue by nevali** [bbcarchdev/spindle#47]
Feature request from indie.

Could be implemented just as multiple submitted `for=URI` parameters (e.g., `for=URI1&for=URI2`)

**Comment by townxelliot** [comment]
Is this resolved? The section about audiences in "Inside Acropolis" (https://bbcarchdev.github.io/inside-acropolis/#audience-groups) isn't clear about whether multiple for= parameters can be passed to a query, and I was unable to find any commits which look like they fix this.
