### ISSUE TITLE
If a transaction fails, librdf models are not emptied

### ISSUE THREAD

**Issue by simeonvandersteen** [bbcarchdev/spindle#82]
Data will be added to the models resulting in duplicated data

**Comment by nevali** [comment]
Hi @simeonvandersteen — was this closed because it was fixed? If so, could you link to the commit that fixed it?

Thank you!

**Comment by simeonvandersteen** [comment]
Yeah is fixed, forgot to mention the issue in the commit message(s).

**Comment by simeonvandersteen** [comment]
0e4e57f96a1ff10b7248a7c9bb3645ff8ebb9399
1206bd78f0430b78ca9d40b3a6d9fc1f9ffe3b5f

**Comment by nevali** [comment]
Brill, thank you 😄
